services:
  redis-main:
    image: redis:8.4.2-alpine@sha256:f08de4b9a28a18f804b650c41a44c65917ab2da69c9b08ed8b11b2633547f4ea
    container_name: redis-main
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-main-data:/data
    restart: unless-stopped

  # redis-cluster:
  #   image: redis:8.4.2-alpine@sha256:f08de4b9a28a18f804b650c41a44c65917ab2da69c9b08ed8b11b2633547f4ea
  #   container_name: redis-cluster
  #   ports:
  #     - "6380:6379"
  #   volumes:
  #     - redis-cluster-data:/data
  #   restart: unless-stopped

volumes:
  redis-main-data:
  redis-cluster-data: